### ISSUE TITLE
Implement Hero Section

### ISSUE THREAD

**Issue by omarghandour** [blackwavesdev/ourwebsite#8]
### The goal of this task is to create a fully responsive Hero Section that contains the **Company's Header** . 
The design should match the given **mockup** and be **mobile-friendly**, using **Tailwind CSS** for styling. This task involves: 
![Image](https://github.com/user-attachments/assets/5f9bc30a-0aef-45d5-aad1-d9d6cdd9a3e9)

**Ensure the Hero Component is responsive across all screen sizes (desktop, tablet, mobile).**
**AND DON'T FORGET TO CHECKOUT TO THE NEW BRANCH "Hero-section"**
Test the Hero Component on desktop, tablet, and mobile devices to ensure layout consistency and functionality.
Assignee:  @mahmoudelhosarry

**Comment by mahmoudelhosarry** [comment]
where is public folder?

**Comment by mahmoudelhosarry** [comment]
where can i find dimentsons?

**Comment by omarghandour** [comment]
we don't have a UI/UX Design , just make it work XD
